//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainDatabaseEntities : DbContext
    {
        public MainDatabaseEntities()
            : base("name=MainDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hardDrive> hardDrives { get; set; }
        public virtual DbSet<normTech> normTeches { get; set; }
        public virtual DbSet<systemCharacteristic> systemCharacteristics { get; set; }
        public virtual DbSet<technic> technics { get; set; }
        public virtual DbSet<employment> employments { get; set; }
        public virtual DbSet<room> rooms { get; set; }
    }
}
